### ISSUE TITLE
Question:  how to access Mopidy-MFE

### ISSUE THREAD

**Issue by GitDougRPi** [LukeMcDonnell/mopidy-MFE#8]
I've installed Mopidy-MFE onto system running PiMusicbox.  How do I actually get to it from a web browser though?   Not as obvious as getting to default PiMusicbox webclient or moped.   Thanks

**Comment by LukeMcDonnell** [comment]
The path to mfe should be http://hostname:port/mfe/ 

Unfortunately, the current PiMusicBox image uses an older version of mopidy which isn't compatible with mfe. I'm not involved with the project personally, but I believe a new version of PiMusicBox is being prepared and should be made available soon.
